QB_CLIENT_ID = "ABTuYoL6dMfSCUeQ6RJ2FtKwONPuQfHZayHAgfzpE0tn6qeGxV"
QB_CLIENT_SECRET = "tZDojaw3yGyP7CC5xCFcYmz2kQKJTFqqnBmoWPsm"
QB_REDIRECT_URI = "http://localhost:8000/callback"
QB_ENVIRONMENT = "production"


[googlesheets]
GSHEETS_TYPE = "service_account"
GSHEETS_PROJECT_ID = "your_google_project_id"
GSHEETS_PRIVATE_KEY_ID = "your_private_key_id"
GSHEETS_PRIVATE_KEY = "your_private_key"
GSHEETS_CLIENT_EMAIL = "your_client_email@your-project.iam.gserviceaccount.com"
GSHEETS_CLIENT_ID = "your_client_id"
GSHEETS_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
GSHEETS_TOKEN_URI = "https://oauth2.googleapis.com/token"
GSHEETS_AUTH_PROVIDER_X509_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
GSHEETS_CLIENT_X509_CERT_URL = "https://www.googleapis.com/robot/v1/metadata/x509/your-client-email%40your-project.iam.gserviceaccount.com"

# Spreadsheet ID for objectives
OBJECTIVES_SPREADSHEET_ID = "your_google_spreadsheet_id"

# Any other configuration values
# APP_THEME = "light"